NAME	:= I_dont_want_to_set_the_world_on_fire
SRC		:= main.cpp \
			Animal.cpp \
			Dog_and_Cat.cpp \
			Brain.cpp
OBJ		:= $(SRC:.cpp=.o)

CC++	:= c++
FLAGS	:= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJ)
	$(CC++) $(FLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp
	$(CC++) $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
